name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: echo
        run: | 
          echo ${{ steps.metadata.outputs.update-type }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
