name: Dependabot auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: echo
        run: | 
          echo ${{ github.actor }} 
          echo ${{ steps.metadata.outputs.update-type }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Enable auto-merge for Dependabot PRs
      #   if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' }}
      #   run: gh pr comment $PR_NUMBER -b "@dependabot merge"
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
